global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'wiki'
    replica: '1'

scrape_configs:
  - job_name: 'blackbox-http'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
          - https://nginx:443
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

  - job_name: 'mediawiki'
    static_configs:
      - targets: ['mediawiki-exporter:8000']

  - job_name: 'mysql'
    static_configs:
      - targets: ['mysqld-exporter:9104']

  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-exporter:9113']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
